spring.application.name=demo
spring.datasource.driverClassName=org.h2.Driver
server.port=8081

spring.h2.console.enabled=true

spring.datasource.url=jdbc:mysql://localhost:3306/tareas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mc2304
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.jpa.show-sql=true
# Muestra las consultas en consola (opcional)
spring.datasource.hikari.pool-name=MiPool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000

logging.level.root=DEBUG
logging.level.com.tarea=TRACE
# Configuración del productor de Kafka
#spring.kafka.producer.bootstrap-servers=localhost:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Configuración del consumidor de Kafka
#spring.kafka.consumer.bootstrap-servers=localhost:9092
#spring.kafka.consumer.group-id=tareas-group
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
